### ISSUE TITLE
Dental Module enhancements 2019-2020

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#572]
Following group discussion:

- [x] related to #540, Please add the following as new specimen options:
Incisor
Canine
Premolar
Molar
Anterior Tooth
Posterior Tooth
*Information regarding associations will be compiled and added later.

- [x] #544 Please add the following zones, images to follow (@nyukyi):
1 - Crown
2 - Root
These apply to all teeth listed above, as well as:
Tooth 1-32
Tooth

- [x] #520 Add Mincer Age to Tooth 1, 16, 17, and 32

- [x] #541 Add maxilla, mandible and cranium to Dentition bone groups

**Comment by SachinPawaskarUNO** [comment]
These enhancements have been completed and are in PROD now.
